In [1]:
import pandas as pd
import vectorbt as vbt

print("VectorBT:", vbt.__version__)
print("Pandas:", pd.__version__)

VectorBT: 1.1.1
Pandas: 3.0.6

In [3]:
import pandas as pd

df = pd.read_csv(
    "../data/XAUUSD_DUKAS_2025_01_ticks.csv",
    header=None
)

df.head()

            0             1       2        3  4  5
0  2025.01.01  23:00:00.455  2625.1  2626.59  0  0
1  2025.01.01  23:00:00.557  2625.7  2626.48  0  0
2  2025.01.01  23:00:00.608  2625.3  2626.48  0  0
3  2025.01.01  23:00:00.659  2625.3  2626.41  0  0
4  2025.01.01  23:00:01.011  2625.5  2626.41  0  0

In [4]:
df.shape

(5798226, 6)

In [6]:
df.columns = [
    "date",
    "time",
    "bid",
    "ask",
    "bid_volume",
    "ask_volume"
]

df.head()

         date          time     bid      ask  bid_volume  ask_volume
0  2025.01.01  23:00:00.455  2625.1  2626.59           0           0
1  2025.01.01  23:00:00.557  2625.7  2626.48           0           0
2  2025.01.01  23:00:00.608  2625.3  2626.48           0           0
3  2025.01.01  23:00:00.659  2625.3  2626.41           0           0
4  2025.01.01  23:00:01.011  2625.5  2626.41           0           0

In [7]:
df["timestamp"] = pd.to_datetime(
    df["date"] + " " + df["time"],
    format="%Y.%m.%d %H:%M:%S.%f"
)

df[["timestamp", "bid", "ask"]].head()

                timestamp     bid      ask
0 2025-01-01 23:00:00.455  2625.1  2626.59
1 2025-01-01 23:00:00.557  2625.7  2626.48
2 2025-01-01 23:00:00.608  2625.3  2626.48
3 2025-01-01 23:00:00.659  2625.3  2626.41
4 2025-01-01 23:00:01.011  2625.5  2626.41

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5798226 entries, 0 to 5798225
Data columns (total 6 columns):
 #   Column  Dtype
---  ------  -----
 0   0       str
 1   1       str
 2   2       float64
 3   3       float64
 4   4       int64
 5   5       int64
dtypes: float64(2), int64(2), str(2)
memory usage: 387.1 MB